# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f42d1e83362bfc050195b8d6aa357a2d83c72802c433ba849fda4a9bae2c12cd64f709c9b2428c2d3e23b74d9d3b460da67fa2124bc803185afbc58107aa3c30

test:
  secret_key_base: f7e154aa7c7475f0fa0cac583b58b3e85b3db12b08a5dac76f26a3ed69ca64457d662df24d8dbf3a8a2e78824c2c5cb012770ee74405627c0ad00ccfde8999f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
